#!/bin/sh

# PROVIDE: xray
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="xray"
rcvar="xray_enable"
command="/usr/local/bin/xray"
config_file="/usr/local/etc/xray/config.json"
command_args="-config ${config_file}"
pidfile="/var/run/${name}.pid"
required_files="${config_file}"
load_rc_config $name
: ${xray_enable:="NO"}

start_precmd="xray_precmd"

xray_precmd() {
    if [ ! -d "/var/run" ]; then
        mkdir -p /var/run
    fi
}

# Modified start command to check if Xray is already running
start_cmd="start_xray"

start_xray() {
    # Check if Xray is already running
    if pgrep -f "/usr/local/bin/xray" > /dev/null; then
        echo "Xray is already running."
    else
        ${command} ${command_args} > /var/log/xray_service.log 2>&1 &
        echo $! > ${pidfile}
        echo "Xray started."
    fi
}

stop_cmd="xray_stop"

xray_stop() {
    if [ -f ${pidfile} ]; then
        kill -TERM $(cat ${pidfile})
        rm -f ${pidfile}
        echo "Xray stopped."
    else
        echo "Xray is not running or pidfile is missing."
    fi
}

run_rc_command "$1"
