#!/bin/sh

# PROVIDE: xray
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="xray"
rcvar="xray_enable"
command="/usr/local/bin/xray"
config_file="/usr/local/etc/xray/config.json"
command_args="-config ${config_file}"
pidfile="/var/run/${name}.pid"
required_files="${config_file}"

load_rc_config $name
: ${xray_enable:="NO"}

start_precmd="xray_precmd"

xray_precmd() {
    if [ ! -d "/var/run" ]; then
        mkdir -p /var/run
    fi
}

start_cmd="${command} ${command_args} > ${log_file} 2>&1 &"  # Run in background and redirect output

run_rc_command "$1"